### ISSUE TITLE
`nem` has been deprecated from Bioconductor

### ISSUE THREAD

**Issue by lcolladotor** [frankkramer-lab/rBiopaxParser#6]
Hi,

I see that `rBiopaxParser` suggests `nem`, however `nem` has been deprecated and is no longer available in Bioconductor-devel. See http://bioconductor.org/checkResults/devel/bioc-LATEST/rBiopaxParser/malbec1-checksrc.html and http://bioconductor.org/packages/release/bioc/html/nem.html.

I see that `nem` seems to be used only for one function at https://github.com/frankkramer-lab/rBiopaxParser/blob/60374c7f0607edccff999a38404913fdf1a6d250/R/visualizeBiopax.R#L287-L326.

I noticed this because `AnnotationHubData` requires `rBiopaxParser` https://github.com/LieberInstitute/GenomicState/runs/661016405#step:8:9071.

Best,
Leo

**Comment by FelixErnst** [comment]
Same for me. Just two months later...

**Comment by tfkillian** [comment]
I'm also experiencing this issue because ExperimentHubData depends downstream on rBiopaxParser, which appears to be only available in R ~3.6, but not R 4.0 (I'm assuming because of the `nem` dependency listed by others above). However, ExperimentHubData requires R 4.0, so I am unable to use this package, of which many of the packages that I maintain depend on. Will this issue be fixed anytime soon? (e.g. will rBiopaxParser be available to R >4.0dev?)

**Comment by FelixErnst** [comment]
@tfkillian Do you mean Bioc `3.11` or Bioc `3.12`? Bioc `3.11` works fine for me, but not Bioc `3.12` (Both with R `4.0`). Can you please post some output of `sessionInfo`? Thanks

**Comment by tfkillian** [comment]
Yes, that's a succinct way of putting it. I have to use the most advanced version of Bioc (`3.12`) because I'm a Bioc package dev. This is the error I get when I try to install `ExperimentHubData`: 

ERROR: dependency ‘rBiopaxParser’ is not available for package ‘AnnotationHubData’
* removing ‘/home/marshalbanana/R/x86_64-pc-linux-gnu-library/4.0/AnnotationHubData’
ERROR: dependency ‘AnnotationHubData’ is not available for package ‘ExperimentHubData’
* removing ‘/home/marshalbanana/R/x86_64-pc-linux-gnu-library/4.0/ExperimentHubData’

sessionInfo() is displayed below:

R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
[1] BiocManager_1.30.10 compiler_4.0.2      tools_4.0.2        
[4] yaml_2.2.1

**Comment by frankkramer** [comment]
@tfkillian @FelixErnst Sorry for the delay. nem dropping out of Bioconductor caught me by surprise. Do you need the functionality of the method imported from nem? I struggled to find an equivalent in other packages. A quick fix would be for me to simply deprecate the method, return NULL and remove nem from suggestions.
Would that be acceptable behavior for your cases?

**Comment by tfkillian** [comment]
@frankkramer since updating to R 4.02, I can't install `ExperimentHubData` (see error above), which is a package which depends downstream on `rBiopaxParser`. If method `nem` were somehow deprecated and removed from suggestions I think that would solve the issue on my end.

**Comment by FelixErnst** [comment]
@frankkramer basically what @tfkillian said. Deprecation might be the least impactful, since as far as I can tell only one function would be affected, which is optional anyway, am I right?

@lcolladotor any additions?

I guess @lshep might also have an opinion regarding the impact on `ExperimentHubData` / `AnnotationHubData`

**Comment by lshep** [comment]
I think removing this functionality or deprecating that function should be find from the prospective of the hubs. The hubs really only utilize the readBiopax function and then require the package when reading the object back it for full functionality.

**Comment by frankkramer** [comment]
The latest commit should fix this issue. I updated the devel branch on Bioconductor as well.

**Comment by frankkramer** [comment]
Bioconductor devel is updated and not throwing errors.
http://bioconductor.org/checkResults/devel/bioc-LATEST/rBiopaxParser/
